# Generated by Django 4.0.1 on 2022-01-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_rename_post_articlecomment_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='post_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='post_url',
            field=models.URLField(null=True),
        ),
    ]
