version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/app/web
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_DB=init5
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123654
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - ./.env.dev
  celery:
    build:
      context: .
    command: celery -A config worker -l info --pool=gevent
    volumes:
      - ./:/home/app/web
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - db
  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - ./:/home/app/web
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - db
  flower:
    build:
      context: .
    command: celery -A config flower --port=5566
    volumes:
      - ./:/home/app/web
    ports:
      - "5566:5566"
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - celery
      - celery-beat
      - redis

volumes:
  postgres_data:

