# Generated by Django 4.0.1 on 2022-01-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_article_number_of_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={},
        ),
    ]
