# Generated by Django 4.0.1 on 2022-01-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_articlecomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={},
        ),
    ]
