# Generated by Django 4.0 on 2022-01-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_changed_rating',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='users_changed_rating',
            field=models.JSONField(null=True),
        ),
    ]
