# Generated by Django 4.0 on 2022-01-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('date_create',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('date_create',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
