# Generated by Django 4.0.1 on 2022-01-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='news',
            name='users_changed_rating',
        ),
    ]
