# Generated by Django 4.0 on 2022-01-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
