# Generated by Django 4.0 on 2022-01-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_name_user_url_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
