# Generated by Django 4.0 on 2022-01-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.SlugField(null=True, verbose_name='http://127.0.0.1:8000/api/users/<django.db.models.fields.CharField>/'),
        ),
    ]
