# Generated by Django 4.0.1 on 2022-01-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
