# Generated by Django 4.0.1 on 2022-01-21 03:03

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/users/standart.png', null=True, upload_to=src.users.models.upload_to),
        ),
    ]
