# Generated by Django 4.0.1 on 2022-01-24 22:38

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/users/standard.png', null=True, upload_to=src.users.models.upload_to),
        ),
    ]
